# -*- coding: utf-8 -*-
"""量化分析.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-nlTf7ZIwXVagXQ-Ud7nkaMnIGqCu2IJ
"""

# !pip install hmmlearn yfinance
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from hmmlearn.hmm import GaussianHMM
from datetime import datetime, timedelta
import os
import pytz
import pandas_market_calendars as mcal

# ==========================================
# 2. 策略參數總控 (Master Config)
# ==========================================
class Config:
    TICKERS = ["MSFT", "AAPL", "GOOGL", "NVDA", "TSLA", "TSM", "META", "AVGO", "ORCL", "AMZN", "MU", "AMD"]

    START_DATE = "2020-01-01"
    # yfinance end date is exclusive, so we add 1 day to include today
    END_DATE = (datetime.now() + timedelta(days=1)).strftime("%Y-%m-%d")

    HMM_COMPONENTS = 3
    SHORT_MA = 10
    LONG_MA_TREND = 200
    LONG_MA_SUPPORT = 50
    RSI_RESET = 55

    # MACD 參數 (標準12,26,9)
    MACD_FAST = 12
    MACD_SLOW = 26
    MACD_SIGNAL = 9

    # 新增圖表繪製開關 (None: 繪製所有圖表; []: 不繪製任何圖表; ["MSFT", "AAPL"]: 繪製指定股票圖表)
    TICKERS_TO_PLOT = [] # 預設為 None，表示繪製所有圖表

# ==========================================
# 3. 核心數據引擎 - 加入 MACD 交叉訊號
# ==========================================
def get_data_and_indicators(ticker):
    print(f"📥 正在下載 {ticker} 數據...")
    raw_df = yf.download(ticker, start=Config.START_DATE, end=Config.END_DATE, progress=False)

    if raw_df.empty:
        print(f"⚠️ {ticker} 無數據，跳過。")
        return None

    df = pd.DataFrame(index=raw_df.index)

    if isinstance(raw_df.columns, pd.MultiIndex):
        df['Close'] = raw_df['Adj Close'][ticker] if 'Adj Close' in raw_df.columns.get_level_values(0) else raw_df['Close'][ticker]
        df['High'] = raw_df['High'][ticker]
        df['Low'] = raw_df['Low'][ticker]
        df['Open'] = raw_df['Open'][ticker]
    else:
        df['Close'] = raw_df['Adj Close'] if 'Adj Close' in raw_df.columns else raw_df['Close']
        df['High'] = raw_df['High']
        df['Low'] = raw_df['Low']
        df['Open'] = raw_df['Open']

    # 移動平均
    df['MA_10'] = df['Close'].rolling(window=Config.SHORT_MA).mean()
    df['MA_50'] = df['Close'].rolling(window=Config.LONG_MA_SUPPORT).mean()
    df['MA_200'] = df['Close'].rolling(window=Config.LONG_MA_TREND).mean()

    # RSI
    delta = df['Close'].diff()
    gain = (delta.where(delta > 0, 0)).ewm(alpha=1/14, adjust=False).mean()
    loss = (-delta.where(delta < 0, 0)).ewm(alpha=1/14, adjust=False).mean()
    rs = gain / loss
    df['RSI'] = 100 - (100 / (1 + rs))

    # MACD 計算
    ema_fast = df['Close'].ewm(span=Config.MACD_FAST, adjust=False).mean()
    ema_slow = df['Close'].ewm(span=Config.MACD_SLOW, adjust=False).mean()
    df['MACD'] = ema_fast - ema_slow
    df['MACD_Signal'] = df['MACD'].ewm(span=Config.MACD_SIGNAL, adjust=False).mean()
    df['MACD_Hist'] = df['MACD'] - df['MACD_Signal']

    # === 優化：新增 MACD 交叉訊號欄位 ===
    df['MACD_Golden_Cross'] = (df['MACD'].shift(1) < df['MACD_Signal'].shift(1)) & (df['MACD'] > df['MACD_Signal'])
    df['MACD_Death_Cross'] = (df['MACD'].shift(1) > df['MACD_Signal'].shift(1)) & (df['MACD'] < df['MACD_Signal'])

    # HMM 特徵
    df['Log_Ret'] = np.log(df['Close'] / df['Close'].shift(1))
    df['Range_Vol'] = (df['High'] - df['Low']) / df['Open']

    return df.dropna()

# ==========================================
# 4. HMM 狀態識別引擎
# ==========================================
def run_hmm(df):
    X = df[['Log_Ret', 'Range_Vol']].values
    model = GaussianHMM(n_components=Config.HMM_COMPONENTS, covariance_type="full", n_iter=1000, random_state=42)
    model.fit(X)
    hidden_states = model.predict(X)

    vol_means = [np.mean(X[hidden_states == i, 1]) for i in range(Config.HMM_COMPONENTS)]
    sorted_idx = np.argsort(vol_means)
    state_map = {old: new for new, old in enumerate(sorted_idx)}
    remapped_states = np.array([state_map[s] for s in hidden_states])

    df['HMM_State'] = remapped_states
    return df

# ==========================================
# 5. 戰情儀表板與視覺化 - 優化 MACD 邏輯 & 標記交叉點
# ==========================================
def plot_dashboard(df, ticker, should_plot=True):
    last_idx = df.index[-1]
    last_row = df.iloc[-1]

    hmm_colors = ['#2ca02c', '#ff7f0e', '#d62728']
    hmm_labels = ['Bull (Low Vol)', 'Neutral (Choppy)', 'Bear (High Vol)']
    current_state = int(last_row['HMM_State'])

    dist_to_ma10 = (last_row['Close'] - last_row['MA_10']) / last_row['MA_10'] * 100
    dist_to_ma50 = (last_row['Close'] - last_row['MA_50']) / last_row['MA_50'] * 100

    # 最新 MACD 狀態
    macd_above_signal = last_row['MACD'] > last_row['MACD_Signal']
    hist_positive = last_row['MACD_Hist'] > 0
    recent_golden = df['MACD_Golden_Cross'].iloc[-1]
    recent_death = df['MACD_Death_Cross'].iloc[-1]

    print("\n" + "="*70)
    print(f"📊 {ticker} 量化戰情室報告 ({last_idx.date()})")
    print("="*70)
    print(f"1. 市場微結構 (HMM):  {hmm_labels[current_state]}")
    print(f"2. 目前股價:          ${last_row['Close']:.2f}")
    print(f"3. 動能指標 (MA10):   ${last_row['MA_10']:.2f} (Gap: {dist_to_ma10:+.2f}%)")
    print(f"4. 機構成本 (MA50):   ${last_row['MA_50']:.2f} (Gap: {dist_to_ma50:+.2f}%)")
    print(f"5. RSI (14):          {last_row['RSI']:.1f}")
    print(f"6. MACD 狀態:         MACD {last_row['MACD']:+.3f} | Signal {last_row['MACD_Signal']:+.3f} | Hist {last_row['MACD_Hist']:+.3f}")
    print(f"   → MACD 在 Signal 上方: {macd_above_signal} | Histogram 正值: {hist_positive}")
    print("-" * 70)


    print("="*70)

    # 繪圖：三子圖 (僅在 should_plot 為 True 時執行)
    if should_plot:
        fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(16, 14), sharex=True, gridspec_kw={'height_ratios': [4, 1, 1]})

        # Price + HMM + MAs
        for i in range(len(df)-1):
            state = int(df['HMM_State'].iloc[i])
            ax1.axvspan(df.index[i], df.index[i+1], color=hmm_colors[state], alpha=0.15)

        ax1.plot(df.index, df['Close'], color='black', lw=1.5, label='Price')
        ax1.plot(df.index, df['MA_10'], color='orange', lw=1.5, label='MA10')
        ax1.plot(df.index, df['MA_50'], color='blue', lw=2, label='MA50')
        ax1.plot(df.index, df['MA_200'], color='gray', lw=1, ls='--', label='MA200')

        # 原有訊號
        breakdown = df[(df['Close'] < df['MA_10']) & (df['Close'].shift(1) >= df['MA_10'].shift(1)) & (df['HMM_State'] > 0)]
        ax1.scatter(breakdown.index, breakdown['Close'], color='red', marker='v', s=80, label='Short Signal', zorder=5)

        reload = df[(df['Low'] <= df['MA_50']*1.02) & (df['Close'] > df['MA_200']) & (df['RSI'] < Config.RSI_RESET)]
        ax1.scatter(reload.index, reload['Low'], color='green', marker='^', s=100, label='Long Signal', zorder=5)

        ax1.set_title(f"{ticker} 多因子策略儀表板 (HMM + MA + RSI + MACD 優化版)", fontsize=14)
        ax1.legend(loc='upper left')
        ax1.grid(True, alpha=0.3)
        ax1.set_yscale('log')

        # RSI
        ax2.plot(df.index, df['RSI'], color='purple', lw=1.5)
        ax2.axhline(70, color='red', ls='--', alpha=0.6)
        ax2.axhline(30, color='green', ls='--', alpha=0.6)
        ax2.axhline(Config.RSI_RESET, color='blue', ls=':', label=f'Reset ({Config.RSI_RESET})')
        ax2.fill_between(df.index, df['RSI'], 70, where=(df['RSI'] >= 70), color='red', alpha=0.3)
        ax2.fill_between(df.index, df['RSI'], 30, where=(df['RSI'] <= 30), color='green', alpha=0.3)
        ax2.set_ylabel('RSI (14)')
        ax2.legend()
        ax2.grid(True, alpha=0.3)

        # MACD - 新增金叉/死叉標記
        ax3.plot(df.index, df['MACD'], color='black', lw=1.2, label='MACD')
        ax3.plot(df.index, df['MACD_Signal'], color='red', lw=1.2, label='Signal')
        ax3.bar(df.index, df['MACD_Hist'], color=np.where(df['MACD_Hist'] > 0, 'green', 'red'), alpha=0.6, width=1, label='Histogram')
        ax3.axhline(0, color='gray', lw=0.8, ls='--')

        golden_dates = df[df['MACD_Golden_Cross']].index
        death_dates = df[df['MACD_Death_Cross']].index
        ax3.scatter(golden_dates, df.loc[golden_dates, 'MACD'], color='lime', marker='^', s=100, label='Golden Cross', zorder=5)
        ax3.scatter(death_dates, df.loc[death_dates, 'MACD'], color='magenta', marker='v', s=100, label='Death Cross', zorder=5)

        ax3.set_ylabel('MACD')
        ax3.legend()
        ax3.grid(True, alpha=0.3)

        plt.tight_layout()
        plt.show()

    return {
        'Ticker': ticker,
        'Last Close': f"${last_row['Close']:.2f}",
        'HMM State': hmm_labels[current_state],
        'MA10 Gap': f"{dist_to_ma10:+.2f}%",
        'MA50 Gap': f"{dist_to_ma50:+.2f}%",
        'RSI': f"{last_row['RSI']:.1f}",
        'MACD > Signal': macd_above_signal,
        'MACD Hist > 0': hist_positive

    }

# ==========================================
# 6. 歷史數據與排程管理 (New Features)
# ==========================================
def save_daily_snapshot(df):
    """
    保存每日分析快照到 CSV
    1. 增加 Date 欄位 (YYYY-MM-DD)
    2. 追加到 history_data.csv
    3. 避免重複寫入同一天的數據
    """
    file_path = "history_data.csv"
    today_str = datetime.now().strftime("%Y-%m-%d")
    
    # 增加 Date 欄位
    df_to_save = df.copy()
    df_to_save['Date'] = today_str
    
    # 檢查檔案是否存在
    if os.path.exists(file_path):
        try:
            existing_df = pd.read_csv(file_path)
            # 檢查是否已有今日數據
            if not existing_df[existing_df['Date'] == today_str].empty:
                print(f"⚠️ {today_str} 的數據已存在，將覆蓋今日數據...")
                # 剔除今日舊數據，保留其他日期的
                existing_df = existing_df[existing_df['Date'] != today_str]
                
            # 合併數據
            final_df = pd.concat([existing_df, df_to_save], ignore_index=True)
        except Exception as e:
            print(f"❌ 讀取歷史檔案失敗: {e}，將建立新檔案。")
            final_df = df_to_save
    else:
        final_df = df_to_save
        
    # 寫入 CSV
    final_df.to_csv(file_path, index=False)
    print(f"✅ 已保存 {today_str} 的分析結果到 {file_path}")

def get_stock_history(ticker):
    """
    讀取特定股票的歷史分析數據
    """
    file_path = "history_data.csv"
    if not os.path.exists(file_path):
        print(f"⚠️ 找不到歷史檔案 {file_path}")
        return None
        
    df = pd.read_csv(file_path)
    ticker_df = df[df['Ticker'] == ticker].sort_values(by='Date')
    return ticker_df

def should_run_now():
    """
    檢查是否應該執行腳本：
    1. 今天是否為 NYSE 交易日
    2. 現在時間是否超過收盤時間 (16:15 ET)
    """
    # 設定時區
    eastern = pytz.timezone('US/Eastern')
    now_et = datetime.now(eastern)
    
    print(f"🕒 當前美東時間: {now_et.strftime('%Y-%m-%d %H:%M:%S')}")

    # 1. 檢查是否為交易日
    nyse = mcal.get_calendar('NYSE')
    schedule = nyse.schedule(start_date=now_et.date(), end_date=now_et.date())
    
    if schedule.empty:
        print("⏸️ 今天不是 NYSE 交易日，跳過執行。")
        return False
        
    print("✅ 今天是有效交易日。")
    
    # 2. 檢查時間 (16:15 後)
    market_close = schedule.iloc[0]['market_close'].to_pydatetime().replace(tzinfo=eastern)
    # 加上 15 分鐘緩衝，確保數據已結算
    target_time = market_close.replace(hour=16, minute=15, second=0, microsecond=0)
    
    if now_et.time() < target_time.time():
        print(f"⏳ 尚未收盤 (目標時間 {target_time.time()})，稍後再試。")
        return False
        
    print("🚀 時間符合，準備執行分析...")
    return True

# ==========================================
# 7. 主程式執行入口
# ==========================================

if __name__ == "__main__":
    if should_run_now():
        all_summaries = []
        print(f"\n🚀 開始批量分析 {len(Config.TICKERS)} 個標的：{Config.TICKERS}\n")

        for ticker in Config.TICKERS:
            data = get_data_and_indicators(ticker)
            if data is not None and len(data) > 200:
                data_analyzed = run_hmm(data)

                # 根據配置決定是否繪製圖表
                should_plot_for_ticker = (Config.TICKERS_TO_PLOT is None) or (ticker in Config.TICKERS_TO_PLOT)
                
                # 注意：如果是在自動化環境跑，可以把 plot_dashboard 的 should_plot 強制設為 False 以節省資源
                # summary = plot_dashboard(data_analyzed, ticker, should_plot=should_plot_for_ticker)
                
                # 為了避免 GitHub Action 報錯，這裡預設保留原有邏輯，但建議在 headless 環境設為 False
                summary = plot_dashboard(data_analyzed, ticker, should_plot=should_plot_for_ticker)
                
                all_summaries.append(summary)
            else:
                print(f"❌ {ticker} 數據不足，跳過分析。\n")

        # 綜合報告表格
        if all_summaries:
            summary_df = pd.DataFrame(all_summaries)
            print("\n" + "="*70)
            print("📊 所有標的量化戰情室綜合報告")
            print("="*70)
            
            # 兼容非 Notebook 環境
            try:
                from IPython.display import display
                display(summary_df)
            except ImportError:
                print(summary_df.to_string())

            # 保存歷史數據
            save_daily_snapshot(summary_df)
            
        else:
            print("\n無數據可供生成綜合報告。")
    else:
        print("💤 條件不符，程式結束。")